// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for PackageArchitecture.
const (
	Amd64 PackageArchitecture = "amd64"
	Arm64 PackageArchitecture = "arm64"
	Arm7  PackageArchitecture = "arm-7"
)

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Module defines model for Module.
type Module struct {
	Name  string `json:"name"`
	Short string `json:"short"`
}

// Package defines model for Package.
type Package struct {
	Architecture PackageArchitecture `json:"architecture"`
	Path         string              `json:"path"`
}

// PackageArchitecture defines model for Package.Architecture.
type PackageArchitecture string

// Release defines model for Release.
type Release struct {
	Checksum     string    `json:"checksum"`
	Mirrors      []string  `json:"mirrors"`
	Modules      []Module  `json:"modules"`
	Packages     []Package `json:"packages"`
	ReleaseNotes string    `json:"release_notes" yaml:"release_notes,omitempty"`
	Version      string    `json:"version"`
}

// Version defines model for Version.
type Version = string

// ReleaseOK defines model for ReleaseOK.
type ReleaseOK struct {
	Data *Release `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// GetReleaseParams defines parameters for GetRelease.
type GetReleaseParams struct {
	// Version version of the release
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// InstallReleaseParams defines parameters for InstallRelease.
type InstallReleaseParams struct {
	// Version version of the release
	Version *Version `form:"version,omitempty" json:"version,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get the information about the latest release of CasaOS
	// (GET /release)
	GetRelease(ctx echo.Context, params GetReleaseParams) error
	// Install a release of CasaOS
	// (POST /release)
	InstallRelease(ctx echo.Context, params InstallReleaseParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetRelease converts echo context to params.
func (w *ServerInterfaceWrapper) GetRelease(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReleaseParams
	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameter("form", true, false, "version", ctx.QueryParams(), &params.Version)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter version: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetRelease(ctx, params)
	return err
}

// InstallRelease converts echo context to params.
func (w *ServerInterfaceWrapper) InstallRelease(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params InstallReleaseParams
	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameter("form", true, false, "version", ctx.QueryParams(), &params.Version)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter version: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InstallRelease(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/release", wrapper.GetRelease)
	router.POST(baseURL+"/release", wrapper.InstallRelease)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xW32/bNhD+V4jbHmUpTdIN0FtWbIMRrAmSYXtIjeIinSUuEqmSJzdqoP99IClZVuwU",
	"zjZgfbJokt99990P3hNkum60IsUW0ido0GBNTMav/iBjpVbuMyebGdmwX8ImbAi9FlySMFQRWoIIpNv9",
	"1JLpIAKFNU2HIQKblVRjgFtjWzGkUCGTZYiAu8adtmykKqDv+wgM2UYrS57MTTBydekWmVZMit0nNk0l",
	"M3TMkr9sYDsZwqq6WkN69wTfG1pDCt8lk8dJOGeTn9DSzWAM+ugJGqMbMiyD6RzZg30NYqDniK88+bli",
	"V5fQRzDaWComo7C6JbMh87Mx2hzhFT1i3VTkPmuyFgun1wglApYIYP2u2Md7vs/7Rfjx0nvNv+hW5f+U",
	"/3vNIgD8Z5xnkOPBV+bNv7HvYr11xifQ7Eb6PL22Yjwvs2FDGOLWKMrFfSdsiIOVOQnpy8+QkFagciW3",
	"lRgOV9RvOm+rAxRCqe6ECDK0qO2iQKbP2O2jRWBLbXh+6cXTvpgxv1JVBymbltz6UysN5ZDeBfMj4qqP",
	"4Bqzh0GSOVE0WSmZMm5NIKza2iFgnf9wDhGgqcffxY+wOkC7QS7nrJOCOBl6mE1y/VlVGvNkcxKfx+cL",
	"rJoS3ySDHt7OYrYVM5q4+PJqpz2RaO7Rymds6CR7vmclZQ/W+ftK9qfJeDXmRz4Uy1q6uvZWJFNt5yZK",
	"5samSVJILtv7ONN1sszozxIr+p2y8jCgWgagN9tdNAY7v+mzcG7tawU3ZG2/j9SEPDkeakysGcWzfeBB",
	"0I9KMz1T412JqiCbflBxHH9Qe95H8LjQ2MhFpnMqSC3okQ0uGAsP1GFdQTo3EOnasW+481mzmd7dyawP",
	"6NtXZ9n0+s5dmmK+o2I05dgUpZVvZpS1RnJ363QcSjHLyNqPrB/IU/Vvf0mYk5ke/4uWS23kF99nJ/LY",
	"yEvqQk+Saq33e9/F9VKstRFSWcaqkqoQqHLRNjmyW7xDi1e3QiuBIqeNzFwDYckhRGFzGe6SERfXS9jR",
	"FTanLsi6IYWNhBTO4pP4DEJz8M6NFeW+C/JtzpWid2OZQwq/Et9sx57dsemFUWM6koxjVb96NuKcnpy8",
	"lL/bc8k0B/URnJ+cH3Pj2VPdR/D2OFMvjys+Kdq6RtMFNfwk6GJpaq+SwHvdhn/DjDeOiW5qDAHyFazt",
	"AXWHyP1fCm9Hhm9I4kESgYd03C1RL9C8OO9WTokwOgQBW+OaULI5TeRYJNCv+r8DAAD///8FDYMQDAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
